### ISSUE TITLE
Your code ignores the trailing edge thickness

### ISSUE THREAD

**Issue by DavidAnderegg** [mbodmer/libairfoil#1]
In the "libairfoil/parsec.py", you forgot the following expressions:

Line 63:
Original:
`Bvec = numpy.array([parsec_params.Z_te, parsec_params.Z_up,`
Fix:
`Bvec = numpy.array([parsec_params.Z_te + parsec_params.dZ_te/2, parsec_params.Z_up,`

Line 70:
Original:
`Bvec = numpy.array([parsec_params.Z_te, parsec_params.Z_lo,`
Fix:
`Bvec = numpy.array([parsec_params.Z_te - parsec_params.dZ_te/2, parsec_params.Z_lo,`

Thanks for sharing your work!
Grüess us Winterthur

**Comment by mbodmer** [comment]
Hi David, sorry for the very late answer.
Thanks a lot for your support. I've integrated your fixes here: https://github.com/mbodmer/libairfoil/commit/a635b869fb19816b51c61cf21fc7ee7406bd3222
E Gruess us Bärn, Marc
